
import React from 'react';
import { Deck, Card, QueueType } from '../types';

interface DeckListProps {
  decks: Deck[];
  cards: Card[];
  onStudy: (deck: Deck) => void;
  onAddDeck: () => void;
  onDeleteDeck: (id: string) => void;
}

export const DeckList: React.FC<DeckListProps> = ({ decks, cards, onStudy, onAddDeck, onDeleteDeck }) => {
  const getDeckStats = (deckId: string) => {
    const deckCards = cards.filter(c => c.deckId === deckId);
    const now = Date.now();
    return {
      new: deckCards.filter(c => c.queue === QueueType.NEW).length,
      learning: deckCards.filter(c => (c.queue === QueueType.LEARNING || c.queue === QueueType.RELEARNING) && c.due <= now).length,
      review: deckCards.filter(c => c.queue === QueueType.REVIEW && c.due <= now).length,
    };
  };

  return (
    <div className="p-6 md:p-12 h-full overflow-y-auto w-full max-w-6xl mx-auto animate-in fade-in duration-500">
      <div className="flex justify-between items-center mb-10 md:mb-16">
        <div>
          <h1 className="text-4xl md:text-6xl font-black tracking-tight text-slate-900 dark:text-white">Decks</h1>
          <div className="flex items-center gap-2 mt-3">
             <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></div>
             <p className="text-[10px] md:text-xs text-slate-400 font-bold uppercase tracking-[0.3em]">Knowledge Base Online</p>
          </div>
        </div>
        <button 
          onClick={onAddDeck}
          className="bg-blue-600 hover:bg-blue-700 text-white p-4 md:px-8 md:py-4 rounded-2xl md:rounded-3xl text-sm font-black transition-all shadow-xl shadow-blue-500/20 active:scale-95 flex items-center gap-3"
        >
          <i className="fa-solid fa-plus text-lg"></i> 
          <span className="hidden md:inline">Create Deck</span>
        </button>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
        {decks.length === 0 ? (
          <div className="col-span-full py-32 text-center opacity-10">
            <i className="fa-solid fa-layer-group text-9xl mb-6"></i>
            <p className="font-black uppercase tracking-[0.5em] text-xl">Empty Collection</p>
          </div>
        ) : (
          decks.map(deck => {
            const stats = getDeckStats(deck.id);
            const totalDue = stats.new + stats.learning + stats.review;
            return (
              <div 
                key={deck.id}
                className="group relative flex flex-col bg-white dark:bg-[#1C1C1E] rounded-[40px] border border-black/[0.03] dark:border-white/[0.03] transition-all hover:shadow-2xl hover:shadow-blue-500/10 p-1"
              >
                <div 
                   onClick={() => totalDue > 0 && onStudy(deck)}
                   className={`flex-1 p-8 rounded-[38px] transition-all ${totalDue > 0 ? 'cursor-pointer' : 'cursor-default opacity-60'}`}
                >
                  <div className="flex justify-between items-start mb-10">
                    <div className="w-12 h-12 bg-blue-500/10 rounded-2xl flex items-center justify-center text-blue-600 group-hover:scale-110 transition-transform">
                       <i className="fa-solid fa-box-archive text-xl"></i>
                    </div>
                    <button 
                      onClick={(e) => { e.stopPropagation(); onDeleteDeck(deck.id); }}
                      className="opacity-0 group-hover:opacity-100 p-2 text-slate-300 hover:text-rose-500 transition-all"
                    >
                      <i className="fa-solid fa-trash-can"></i>
                    </button>
                  </div>

                  <h3 className="font-black text-2xl mb-2 text-slate-800 dark:text-slate-100 line-clamp-2">{deck.name}</h3>
                  <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-8">Generated by MD-Engine</p>
                  
                  <div className="flex items-center gap-5">
                    <div className="flex flex-col">
                      <span className="text-[9px] font-black text-blue-500 uppercase tracking-tighter mb-1">New</span>
                      <span className="text-xl font-black">{stats.new}</span>
                    </div>
                    <div className="w-px h-6 bg-slate-100 dark:bg-slate-800"></div>
                    <div className="flex flex-col">
                      <span className="text-[9px] font-black text-rose-500 uppercase tracking-tighter mb-1">Learn</span>
                      <span className="text-xl font-black">{stats.learning}</span>
                    </div>
                    <div className="w-px h-6 bg-slate-100 dark:bg-slate-800"></div>
                    <div className="flex flex-col">
                      <span className="text-[9px] font-black text-emerald-500 uppercase tracking-tighter mb-1">Due</span>
                      <span className="text-xl font-black">{stats.review}</span>
                    </div>
                  </div>
                </div>
                
                {totalDue > 0 && (
                  <div className="absolute bottom-6 right-8">
                     <div className="w-14 h-14 rounded-full bg-slate-900 dark:bg-blue-600 text-white flex items-center justify-center shadow-2xl group-hover:scale-110 transition-all">
                       <i className="fa-solid fa-play text-lg ml-1"></i>
                     </div>
                  </div>
                )}
              </div>
            );
          })
        )}
      </div>
    </div>
  );
};
